version: '3'
services:
  app:
    image: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: marek123
    ports:
      - 80:80
      - 443:443
    links:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./dbData/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: marek123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: marek123
    links:
      - db